# Generated by Django 4.2.11 on 2024-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_ingredients_alter_recipe_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.ManyToManyField(blank=True, related_name='ingredient', to='recipe.recipe'),
        ),
    ]
