# Generated by Django 4.2.11 on 2024-04-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_ingredient_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp')], default=None)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipe.ingredient')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipe.recipe')),
            ],
        ),
    ]
