# Generated by Django 4.2.11 on 2024-04-22 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_ingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_numer', models.IntegerField(default=0)),
                ('step_instruction', models.CharField(max_length=120)),
                ('rec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_id', to='recipe.recipe')),
            ],
        ),
    ]
