# Generated by Django 4.2.11 on 2024-04-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_recipe_instructions_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='step_numer',
            new_name='step_number',
        ),
    ]
