# Generated by Django 4.2.11 on 2024-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_rename_picture_recipe_cuisine_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('Italian', 'Italian'), ('French', 'French'), ('Asian', 'Asian'), ('Indian', 'Indian'), ('Czech', 'Czech'), ('', '')], default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(),
        ),
    ]
