# Generated by Django 4.2.11 on 2024-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_cuisine_alter_recipe_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Instructions',
        ),
    ]
